version: '3'
services:
  # later rewrite gateway service with go or php and auth
  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "8080:80"
    volumes:
      - "./docker/gateway/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - baseNetwork
  chat-api:
    image: nginx:alpine
    container_name: chat-api
    ports:
      - "8081:80"
    volumes:
      - "./api-chat/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./api-chat:/var/www/chat"
    networks:
      - baseNetwork
  chat:
    build:
      dockerfile: "docker/Dockerfile"
      context: "api-chat"
    container_name: chat
    entrypoint: sh -c "php /var/www/chat/artisan migrate --force && php-fpm"
    environment:
      - APP_ENV=local
      - APP_KEY=base64:7t3iJGYKu1jqjeEQixGEL8mXwCr6XgVRmd6ryRII3Jo=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-chat
      - DB_PORT=3306
      - DB_DATABASE="$CHAT_DATABASE_NAME$"
      - DB_USERNAME="$CHAT_DATABASE_USER$"
      - DB_PASSWORD="$CHAT_DATABASE_PASSWORD$"
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    volumes:
      - "./api-chat:/var/www/chat"
    networks:
      - baseNetwork
    depends_on:
      - mysql-chat
  mysql-chat:
    image: mariadb:latest
    container_name: mysql
    environment:
      MARIADB_ROOT_PASSWORD: "123456"
      MARIADB_DATABASE: "$CHAT_DATABASE_NAME$"
      MARIADB_USER: "$CHAT_DATABASE_USER$"
      MARIADB_PASSWORD: "$CHAT_DATABASE_PASSWORD$"
    networks:
      - baseNetwork
    volumes:
      - "./docker-mysql-data:/var/lib/mysql"
  frontent:
    build:
      dockerfile: "docker/Dockerfile"
      context: 'frontend'
    ports:
      - "80:8080"
    networks:
      - baseNetwork
networks:
  baseNetwork:
    driver: bridge